import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="grid grid-cols-4 gap-20 mt-15 h-[calc(100vh-130px)]">
          <Sidebar />
          <main className="col-span-3 mr-20  border-[#BFC3CA] border-solid border-[2px] shadow-2xl bg-bg">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
